version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    env_file: 
      - ./backend/config/.env

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile-dev
  #   volumes:
  #     - ./frontend:/home/app/
  #   network_mode: "host"
